import { 
  BarChart3, 
  DollarSign, 
  TrendingUp, 
  Shield, 
  Info,
  AlertTriangle,
  CheckCircle,
  ArrowRight
} from "lucide-react"

const poolBenefits = [
  {
    title: "Earn Trading Fees",
    description: "Get a share of all trading fees generated by the pool",
    icon: DollarSign,
    details: [
      "Fees are distributed proportionally to your share",
      "Earnings are automatically added to your position",
      "No need to manually claim rewards"
    ]
  },
  {
    title: "Passive Income",
    description: "Your tokens work for you while you sleep",
    icon: TrendingUp,
    details: [
      "Earn rewards without active trading",
      "Compound your earnings over time",
      "Diversify your income sources"
    ]
  },
  {
    title: "Low Risk",
    description: "Generally lower risk compared to active trading",
    icon: Shield,
    details: [
      "No need to time the market",
      "Reduced volatility exposure",
      "Steady, predictable returns"
    ]
  }
]

const howItWorks = [
  {
    step: 1,
    title: "Choose a Pool",
    description: "Select a liquidity pool that matches your investment strategy",
    details: [
      "Browse available pools on the Pools page",
      "Check the current APR (Annual Percentage Rate)",
      "Review the pool's trading volume and liquidity",
      "Consider the risk level and your investment goals"
    ],
    tips: [
      "Start with popular pairs like SOL/USDC",
      "Check the pool's historical performance",
      "Consider the token volatility"
    ]
  },
  {
    step: 2,
    title: "Add Liquidity",
    description: "Deposit equal values of both tokens into the pool",
    details: [
      "Click 'Add Liquidity' on your chosen pool",
      "Enter the amount of the first token",
      "The second token amount will be calculated automatically",
      "Review the transaction details and fees",
      "Confirm the transaction in your wallet"
    ],
    tips: [
      "You need equal dollar values of both tokens",
      "Start with small amounts to test the process",
      "Keep some tokens outside the pool for flexibility"
    ]
  },
  {
    step: 3,
    title: "Earn Rewards",
    description: "Start earning trading fees automatically",
    details: [
      "Your LP tokens represent your share of the pool",
      "Trading fees are distributed to all liquidity providers",
      "Your earnings compound automatically",
      "Monitor your position in the Portfolio section"
    ],
    tips: [
      "Higher trading volume means more fees",
      "Popular pairs typically generate more fees",
      "Check your earnings regularly"
    ]
  },
  {
    step: 4,
    title: "Remove Liquidity",
    description: "Withdraw your tokens and accumulated fees anytime",
    details: [
      "Go to your position in the Portfolio section",
      "Click 'Remove Liquidity'",
      "Choose how much to withdraw (partial or full)",
      "Confirm the transaction in your wallet",
      "Receive both tokens plus accumulated fees"
    ],
    tips: [
      "You can remove liquidity anytime",
      "Consider gas fees when making small withdrawals",
      "Your final amount may differ due to price changes"
    ]
  }
]

const risksAndConsiderations = [
  {
    title: "Impermanent Loss",
    description: "Potential loss when token prices change relative to each other",
    details: [
      "Occurs when one token's price changes significantly",
      "More likely with volatile token pairs",
      "Can be mitigated by choosing stable pairs",
      "May be offset by trading fee earnings"
    ],
    mitigation: "Choose stable pairs or pairs you believe will maintain similar price movements"
  },
  {
    title: "Smart Contract Risk",
    description: "Risk of bugs or exploits in the underlying smart contracts",
    details: [
      "All DeFi protocols carry some smart contract risk",
      "DeFi Nexus uses audited and battle-tested contracts",
      "Risk is generally low but not zero",
      "Never invest more than you can afford to lose"
    ],
    mitigation: "Only invest amounts you can afford to lose and diversify your investments"
  },
  {
    title: "Market Risk",
    description: "Risk of overall market downturns affecting your investments",
    details: [
      "Crypto markets can be highly volatile",
      "Pool values can decrease during market crashes",
      "Trading volume may decrease during bear markets",
      "Fees may be lower during low-activity periods"
    ],
    mitigation: "Diversify across different pools and asset types"
  }
]

const popularPools = [
  {
    pair: "SOL/USDC",
    apr: "8.5%",
    volume: "$2.4M",
    liquidity: "$45.2M",
    risk: "Low",
    description: "Most popular and stable pair on Solana"
  },
  {
    pair: "SOL/USDT",
    apr: "7.8%",
    volume: "$1.8M",
    liquidity: "$32.1M",
    risk: "Low",
    description: "Alternative stable pair with good liquidity"
  },
  {
    pair: "USDC/USDT",
    apr: "3.2%",
    volume: "$950K",
    liquidity: "$18.7M",
    risk: "Very Low",
    description: "Stablecoin pair with minimal impermanent loss risk"
  }
]

export default function PoolsOverviewPage() {
  return (
    <div className="max-w-4xl">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center space-x-2 mb-4">
          <BarChart3 className="h-8 w-8 text-primary" />
          <h1 className="text-3xl font-bold">What are Liquidity Pools?</h1>
        </div>
        <p className="text-lg text-muted-foreground">
          Learn how liquidity pools work and how you can earn passive income by providing 
          liquidity to trading pairs on DeFi Nexus. It's one of the most popular ways to 
          earn rewards in DeFi.
        </p>
      </div>

      {/* What are Pools */}
      <div className="mb-12 p-6 rounded-lg border bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-950/20 dark:to-purple-950/20">
        <h2 className="text-xl font-semibold mb-4 flex items-center">
          <Info className="h-5 w-5 mr-2 text-blue-500" />
          Understanding Liquidity Pools
        </h2>
        <p className="text-muted-foreground mb-4">
          A liquidity pool is a collection of tokens locked in a smart contract that enables 
          trading on decentralized exchanges. When you provide liquidity, you're essentially 
          becoming a market maker and earning a share of all trading fees.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
          <div className="p-3 bg-white/50 dark:bg-black/20 rounded-lg">
            <strong>How it works:</strong> You deposit two tokens in equal value, receive LP tokens representing your share
          </div>
          <div className="p-3 bg-white/50 dark:bg-black/20 rounded-lg">
            <strong>Earnings:</strong> You earn a portion of all trading fees generated by the pool
          </div>
          <div className="p-3 bg-white/50 dark:bg-black/20 rounded-lg">
            <strong>Flexibility:</strong> You can add or remove liquidity anytime
          </div>
        </div>
      </div>

      {/* Benefits */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold mb-6">Why Provide Liquidity?</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {poolBenefits.map((benefit, index) => (
            <div key={index} className="p-6 rounded-lg border bg-card">
              <div className="flex items-center space-x-3 mb-4">
                <div className="p-2 rounded-lg bg-primary/10">
                  <benefit.icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold">{benefit.title}</h3>
              </div>
              <p className="text-muted-foreground text-sm mb-4">{benefit.description}</p>
              <ul className="space-y-2">
                {benefit.details.map((detail, detailIndex) => (
                  <li key={detailIndex} className="text-xs text-muted-foreground flex items-start">
                    <CheckCircle className="h-3 w-3 text-green-500 mt-0.5 mr-2 flex-shrink-0" />
                    {detail}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>

      {/* How It Works */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold mb-6">How to Get Started</h2>
        <div className="space-y-8">
          {howItWorks.map((step, index) => (
            <div key={index} className="border rounded-lg p-6 bg-card">
              <div className="flex items-start space-x-4">
                <div className="flex-shrink-0">
                  <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-semibold">
                    {step.step}
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                  <p className="text-muted-foreground mb-4">{step.description}</p>
                  
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    <div>
                      <h4 className="font-medium mb-3 flex items-center">
                        <CheckCircle className="h-4 w-4 mr-2 text-green-500" />
                        Step-by-step:
                      </h4>
                      <ul className="space-y-2">
                        {step.details.map((detail, detailIndex) => (
                          <li key={detailIndex} className="text-sm text-muted-foreground flex items-start">
                            <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2 mr-3 flex-shrink-0"></span>
                            {detail}
                          </li>
                        ))}
                      </ul>
                    </div>
                    
                    <div>
                      <h4 className="font-medium mb-3 flex items-center">
                        <TrendingUp className="h-4 w-4 mr-2 text-yellow-500" />
                        Pro Tips:
                      </h4>
                      <ul className="space-y-2">
                        {step.tips.map((tip, tipIndex) => (
                          <li key={tipIndex} className="text-sm text-muted-foreground flex items-start">
                            <span className="w-1.5 h-1.5 rounded-full bg-yellow-500 mt-2 mr-3 flex-shrink-0"></span>
                            {tip}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Popular Pools */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold mb-6">Popular Pools</h2>
        <div className="space-y-4">
          {popularPools.map((pool, index) => (
            <div key={index} className="border rounded-lg p-6 bg-card">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-lg font-semibold">{pool.pair}</h3>
                  <p className="text-sm text-muted-foreground">{pool.description}</p>
                </div>
                <div className="text-right">
                  <div className="text-lg font-semibold text-green-600">{pool.apr}</div>
                  <div className="text-xs text-muted-foreground">APR</div>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <div className="text-muted-foreground">Volume (24h)</div>
                  <div className="font-medium">{pool.volume}</div>
                </div>
                <div>
                  <div className="text-muted-foreground">Total Liquidity</div>
                  <div className="font-medium">{pool.liquidity}</div>
                </div>
                <div>
                  <div className="text-muted-foreground">Risk Level</div>
                  <div className={`font-medium ${
                    pool.risk === 'Very Low' ? 'text-green-600' :
                    pool.risk === 'Low' ? 'text-yellow-600' :
                    'text-red-600'
                  }`}>{pool.risk}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Risks and Considerations */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold mb-6">Risks and Considerations</h2>
        <div className="space-y-6">
          {risksAndConsiderations.map((risk, index) => (
            <div key={index} className="border rounded-lg p-6 bg-card">
              <h3 className="text-lg font-semibold mb-2">{risk.title}</h3>
              <p className="text-muted-foreground mb-4">{risk.description}</p>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-medium mb-3 text-red-600">Potential Risks:</h4>
                  <ul className="space-y-2">
                    {risk.details.map((detail, detailIndex) => (
                      <li key={detailIndex} className="text-sm text-muted-foreground flex items-start">
                        <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                        {detail}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h4 className="font-medium mb-3 text-green-600">How to Mitigate:</h4>
                  <p className="text-sm text-muted-foreground">{risk.mitigation}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Important Notes */}
      <div className="mb-12 p-6 rounded-lg border bg-gradient-to-r from-yellow-50 to-orange-50 dark:from-yellow-950/20 dark:to-orange-950/20">
        <h3 className="text-lg font-semibold mb-2 flex items-center">
          <AlertTriangle className="h-5 w-5 mr-2 text-yellow-500" />
          Important Notes
        </h3>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li>• Liquidity provision involves risks - never invest more than you can afford to lose</li>
          <li>• Impermanent loss can occur when token prices change relative to each other</li>
          <li>• Past performance doesn't guarantee future results</li>
          <li>• Always do your own research before investing</li>
          <li>• Consider starting with small amounts to understand the process</li>
        </ul>
      </div>

      {/* Next Steps */}
      <div className="p-6 rounded-lg border bg-card">
        <h3 className="text-lg font-semibold mb-2">Ready to Start Earning?</h3>
        <p className="text-muted-foreground text-sm mb-4">
          Now that you understand how liquidity pools work, you're ready to start earning passive income!
        </p>
        <div className="flex flex-wrap gap-3">
          <a
            href="/docs/pools/add-liquidity"
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary bg-primary/10 rounded-md hover:bg-primary/20 transition-colors"
          >
            <ArrowRight className="h-4 w-4 mr-2" />
            How to Add Liquidity
          </a>
          <a
            href="/docs/pools/remove-liquidity"
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary bg-primary/10 rounded-md hover:bg-primary/20 transition-colors"
          >
            <ArrowRight className="h-4 w-4 mr-2" />
            How to Remove Liquidity
          </a>
          <a
            href="/docs/resources/faq"
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary bg-primary/10 rounded-md hover:bg-primary/20 transition-colors"
          >
            <Info className="h-4 w-4 mr-2" />
            FAQ
          </a>
        </div>
      </div>
    </div>
  )
}






















