import { 
  HelpCircle, 
  ChevronDown, 
  ChevronUp,
  Search,
  Filter
} from "lucide-react"

const faqCategories = [
  {
    title: "Getting Started",
    questions: [
      {
        question: "How do I connect my wallet to DeFi Nexus?",
        answer: "Click the 'Connect Wallet' button in the header, select your preferred wallet (Phantom, Solflare, etc.), and approve the connection. Your wallet address will be displayed once connected."
      },
      {
        question: "What wallets are supported?",
        answer: "DeFi Nexus supports all major Solana wallets including Phantom, Solflare, Backpack, Glow, and hardware wallets like Ledger. We're constantly adding support for new wallets."
      },
      {
        question: "Do I need SOL to use the platform?",
        answer: "Yes, you need SOL for transaction fees. Each transaction on Solana requires a small amount of SOL to pay for gas fees. We recommend keeping at least 0.01 SOL in your wallet."
      },
      {
        question: "Is DeFi Nexus safe to use?",
        answer: "Yes, DeFi Nexus is built with security as a top priority. We use audited smart contracts, implement best practices for wallet integration, and never store your private keys. Always verify transactions before confirming."
      }
    ]
  },
  {
    title: "Trading",
    questions: [
      {
        question: "How do I swap tokens?",
        answer: "Navigate to the Swap page, select your input and output tokens, enter the amount you want to swap, review the details, and confirm the transaction in your wallet."
      },
      {
        question: "What is slippage and how does it work?",
        answer: "Slippage is the difference between the expected price and the actual execution price. We set a default slippage of 0.5% to protect against price movements during transaction confirmation."
      },
      {
        question: "Why is my transaction failing?",
        answer: "Transactions can fail due to insufficient SOL for gas fees, slippage tolerance being too low, insufficient token balance, or network congestion. Check your balance and try increasing slippage tolerance."
      },
      {
        question: "How do I trade perpetuals?",
        answer: "Go to the Perpetuals page, select your trading pair, choose long or short position, set your leverage, and confirm the trade. Make sure you understand the risks of leveraged trading."
      }
    ]
  },
  {
    title: "Liquidity & Pools",
    questions: [
      {
        question: "How do I provide liquidity?",
        answer: "Navigate to the Pools page, select a pool, enter the amount of tokens you want to provide, and confirm the transaction. You'll receive LP tokens representing your share of the pool."
      },
      {
        question: "How do I earn fees from liquidity provision?",
        answer: "When you provide liquidity, you earn a portion of the trading fees generated by the pool. Fees are automatically added to the pool and reflected in your LP token value."
      },
      {
        question: "What is impermanent loss?",
        answer: "Impermanent loss occurs when the price ratio of tokens in a pool changes. It's 'impermanent' because it can be recovered if prices return to their original ratio."
      },
      {
        question: "How do I remove liquidity?",
        answer: "Go to the Pools page, find your position, click 'Remove Liquidity', enter the amount or percentage to remove, and confirm the transaction."
      }
    ]
  },
  {
    title: "Lending",
    questions: [
      {
        question: "How does lending work?",
        answer: "You can lend your tokens to earn interest. Your tokens are used by borrowers, and you earn interest based on the utilization rate of the lending pool."
      },
      {
        question: "What is the collateral factor?",
        answer: "The collateral factor determines how much you can borrow against your supplied assets. Higher collateral factors allow for more borrowing power but may have higher risk."
      },
      {
        question: "How do I borrow assets?",
        answer: "First, supply assets as collateral, then you can borrow other assets up to your borrowing limit. You'll need to maintain a healthy collateral ratio to avoid liquidation."
      },
      {
        question: "What happens if I get liquidated?",
        answer: "If your collateral ratio falls below the liquidation threshold, your collateral may be liquidated to repay your debt. This helps maintain the health of the lending protocol."
      }
    ]
  },
  {
    title: "Staking",
    questions: [
      {
        question: "How do I stake tokens?",
        answer: "Go to the Stake page, select a validator or staking pool, enter the amount you want to stake, and confirm the transaction. You'll start earning rewards immediately."
      },
      {
        question: "How are staking rewards calculated?",
        answer: "Staking rewards are calculated based on the validator's performance, network inflation rate, and your stake amount. Rewards are typically distributed daily."
      },
      {
        question: "Can I unstake my tokens anytime?",
        answer: "Yes, you can unstake your tokens, but there's usually a cooldown period (typically 2-3 days) before your tokens become available for withdrawal."
      },
      {
        question: "What is the difference between validators?",
        answer: "Validators differ in their commission rates, uptime, and performance. Choose validators with good uptime and reasonable commission rates for optimal rewards."
      }
    ]
  },
  {
    title: "Technical",
    questions: [
      {
        question: "What blockchain does DeFi Nexus use?",
        answer: "DeFi Nexus is built on Solana, a high-performance blockchain known for its fast transaction speeds and low fees."
      },
      {
        question: "How fast are transactions?",
        answer: "Solana transactions typically confirm within 1-2 seconds, making it one of the fastest blockchains available."
      },
      {
        question: "What are the transaction fees?",
        answer: "Transaction fees on Solana are very low, typically less than $0.01 per transaction, paid in SOL."
      },
      {
        question: "Is there an API available?",
        answer: "Yes, we provide a comprehensive API for developers. Check our API documentation for endpoints and integration examples."
      }
    ]
  }
]

export default function FAQPage() {
  return (
    <div className="max-w-4xl">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center space-x-2 mb-4">
          <HelpCircle className="h-8 w-8 text-primary" />
          <h1 className="text-3xl font-bold">Frequently Asked Questions</h1>
        </div>
        <p className="text-lg text-muted-foreground">
          Find answers to the most common questions about DeFi Nexus. Can't find what you're looking for? 
          Join our Discord community for additional support.
        </p>
      </div>

      {/* Search */}
      <div className="mb-8">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search FAQ..."
            className="w-full pl-10 pr-4 py-3 border rounded-lg bg-background focus:outline-none focus:ring-2 focus:ring-primary"
          />
        </div>
      </div>

      {/* FAQ Categories */}
      <div className="space-y-8">
        {faqCategories.map((category, categoryIndex) => (
          <div key={categoryIndex} className="border rounded-lg bg-card">
            <div className="p-6 border-b">
              <h2 className="text-xl font-semibold">{category.title}</h2>
            </div>
            <div className="divide-y">
              {category.questions.map((faq, faqIndex) => (
                <details key={faqIndex} className="group">
                  <summary className="p-6 cursor-pointer hover:bg-muted/50 transition-colors">
                    <div className="flex items-center justify-between">
                      <h3 className="font-medium text-left pr-4">{faq.question}</h3>
                      <ChevronDown className="h-5 w-5 text-muted-foreground group-open:rotate-180 transition-transform flex-shrink-0" />
                    </div>
                  </summary>
                  <div className="px-6 pb-6">
                    <p className="text-muted-foreground leading-relaxed">{faq.answer}</p>
                  </div>
                </details>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Still Need Help */}
      <div className="mt-12 p-6 rounded-lg border bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-950/20 dark:to-purple-950/20">
        <h3 className="text-lg font-semibold mb-2">Still Need Help?</h3>
        <p className="text-muted-foreground text-sm mb-4">
          Can't find the answer you're looking for? Our community and support team are here to help.
        </p>
        <div className="flex flex-wrap gap-3">
          <a
            href="https://discord.gg/definexus"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary bg-primary/10 rounded-md hover:bg-primary/20 transition-colors"
          >
            <HelpCircle className="h-4 w-4 mr-2" />
            Discord Community
          </a>
          <a
            href="mailto:support@definexus.com"
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary bg-primary/10 rounded-md hover:bg-primary/20 transition-colors"
          >
            <HelpCircle className="h-4 w-4 mr-2" />
            Email Support
          </a>
          <a
            href="/docs/resources/troubleshooting"
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary bg-primary/10 rounded-md hover:bg-primary/20 transition-colors"
          >
            <Filter className="h-4 w-4 mr-2" />
            Troubleshooting Guide
          </a>
        </div>
      </div>
    </div>
  )
}






















