name: Deploy to AWS with Slack Notifications

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Deployment Started
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "channel": "#defi-nexus-deployments",
              "username": "DeFi Nexus Bot",
              "icon_emoji": ":rocket:",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "🚀 DeFi Nexus Frontend Deployment Started",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Message",
                      "value": "${{ github.event.head_commit.message }}",
                      "short": false
                    }
                  ],
                  "footer": "DeFi Nexus CI/CD",
                  "ts": ${{ github.event.head_commit.timestamp }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          ESLINT_NO_DEV_ERRORS: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync ./out/ s3://defi-nexus-frontend --delete
          echo "✅ Assets uploaded to S3 successfully"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          echo "✅ CloudFront cache invalidated successfully"

      - name: Notify Deployment Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#defi-nexus-deployments'
          custom_payload: |
            {
              "channel": "#defi-nexus-deployments",
              "username": "DeFi Nexus Bot",
              "icon_emoji": ":white_check_mark:",
              "attachments": [
                {
                  "color": "good",
                  "title": "✅ DeFi Nexus Frontend Deployed Successfully!",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Duration",
                      "value": "${{ job.duration }}",
                      "short": true
                    },
                    {
                      "title": "Live URL",
                      "value": "<https://defi-nexus.com|🌐 defi-nexus.com>",
                      "short": true
                    },
                    {
                      "title": "CloudFront",
                      "value": "<https://dodaddu.cloudfront.net|📊 dodaddu.cloudfront.net>",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Site",
                      "url": "https://defi-nexus.com",
                      "style": "primary"
                    },
                    {
                      "type": "button",
                      "text": "View Commit",
                      "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
                    }
                  ],
                  "footer": "DeFi Nexus CI/CD",
                  "ts": ${{ github.event.head_commit.timestamp }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Deployment Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#defi-nexus-deployments'
          custom_payload: |
            {
              "channel": "#defi-nexus-deployments",
              "username": "DeFi Nexus Bot",
              "icon_emoji": ":x:",
              "attachments": [
                {
                  "color": "danger",
                  "title": "❌ DeFi Nexus Frontend Deployment Failed!",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Failed Step",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Logs",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "style": "danger"
                    },
                    {
                      "type": "button",
                      "text": "View Commit",
                      "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
                    }
                  ],
                  "footer": "DeFi Nexus CI/CD",
                  "ts": ${{ github.event.head_commit.timestamp }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}



