name: Slack Deployment Start Notifications

on:
  workflow_run:
    workflows: ["Deploy DeFi Nexus"]
    types: [requested]

jobs:
  notify-start:
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify Slack on Deployment Start
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "channel": "#defi-nexus-deployments",
              "username": "DeFi Nexus Bot",
              "icon_emoji": ":rocket:",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "🚀 DeFi Nexus Frontend Deployment Started",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.event.workflow_run.head_branch }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.workflow_run.head_sha }}|${{ github.event.workflow_run.head_sha }}>",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.event.workflow_run.head_commit.author.name }}",
                      "short": true
                    },
                    {
                      "title": "Message",
                      "value": "${{ github.event.workflow_run.head_commit.message }}",
                      "short": false
                    }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Progress",
                      "url": "${{ github.event.workflow_run.html_url }}",
                      "style": "primary"
                    }
                  ],
                  "footer": "DeFi Nexus CI/CD",
                  "ts": ${{ github.event.workflow_run.created_at }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
