name: Slack Deployment Notifications

on:
  workflow_run:
    workflows: ["Deploy DeFi Nexus"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: always() # Run regardless of workflow success/failure
    
    steps:
      - name: Notify Slack on Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#defi-nexus-deployments'
          text: |
            🚀 **DeFi Nexus Frontend Deployed Successfully!**
            
            **Branch:** `${{ github.event.workflow_run.head_branch }}`
            **Commit:** `${{ github.event.workflow_run.head_sha }}`
            **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
            **Message:** ${{ github.event.workflow_run.head_commit.message }}
            **Duration:** ${{ github.event.workflow_run.run_duration_ms }}ms
            
            **🌐 Live URL:** https://defi-nexus.com
            **📊 CloudFront:** https://dodaddu.cloudfront.net
            
            ✅ Build completed successfully
            ✅ Assets uploaded to S3
            ✅ CloudFront cache invalidated
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#defi-nexus-deployments'
          text: |
            ❌ **DeFi Nexus Frontend Deployment Failed!**
            
            **Branch:** `${{ github.event.workflow_run.head_branch }}`
            **Commit:** `${{ github.event.workflow_run.head_sha }}`
            **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
            **Message:** ${{ github.event.workflow_run.head_commit.message }}
            **Duration:** ${{ github.event.workflow_run.run_duration_ms }}ms
            
            **🔍 Check the logs:** ${{ github.event.workflow_run.html_url }}
            
            ⚠️ Please investigate and fix the deployment issues
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Cancelled
        if: ${{ github.event.workflow_run.conclusion == 'cancelled' }}
        uses: 8398a7/action-slack@v3
        with:
          status: cancelled
          channel: '#defi-nexus-deployments'
          text: |
            ⏹️ **DeFi Nexus Frontend Deployment Cancelled**
            
            **Branch:** `${{ github.event.workflow_run.head_branch }}`
            **Commit:** `${{ github.event.workflow_run.head_sha }}`
            **Author:** ${{ github.event.workflow_run.head_commit.author.name }}
            **Message:** ${{ github.event.workflow_run.head_commit.message }}
            
            **🔍 Check the logs:** ${{ github.event.workflow_run.html_url }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
